<?php

namespace Aranyasen\HL7\Segments;

use Aranyasen\HL7\Segment;

/**
 * ORC segment class
 * Ref: https://hl7-definition.caristix.com/v2/HL7v2.8/Segments/IPC
 */
class IPC extends Segment
{
    public function __construct(array $fields = null)
    {
        parent::__construct('IPC', $fields);
    }
    
    
    //  *** SETTERS ***
    
    // POSITIONS 1 THROUGH 4 ARE EI DATATYPES:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/EI
    
	/* setAccessionIdentifier,  corresponds to the Filler Order
	 * 
     * Entity Identifier
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function setAccessionIdentifier($value, int $position = 1)
    {
        return $this->setField($position, $value);
    }
    /* setRequestedProcedureId
     * Entity Identifier, 16 maximum chars
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function setRequestedProcedureId($value, int $position = 2)
    {
        return $this->setField($position, $value);
    }
    /* setStudyInstanceUid
     * Entity Identifier, 64 maximum chars, unique id generated by the RIS or DICOM 
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function setStudyInstanceUid($value, int $position = 3)
    {
        return $this->setField($position, $value);
    }
    /* setScheduledProcedureStepId
     * Entity Identifier, 16 maximum chars
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function setScheduledProcedureStepId($value, int $position = 4)
    {
        return $this->setField($position, $value);
    }
    
    
    
    // POSITIONS 5 & 6 ARE CWE DATATYPES:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/CWE
    
    /* setModality and exam encoding
    
     * (0008,0060) 5.1 is same as this
     * See below for list of valid values for 5.1
     * 5.2 is  descriptive text for exam
     * 5.3 is  Name Of Coding System, see below
     * 5.4 is  Alternate Identifier, see below
     * 5.5 is  Alternate Text, see below
     * 5.6 is  Name Of Alternate Coding System, see below
     * 5.7 is  Name Of Coding System, see below
    */
    public function setModality($value, int $position = 5)
    {
        return $this->setField($position, $value);
    }

    public function setProtocolCode($value, int $position = 6)
    {
        return $this->setField($position, $value);
    }
    
    // POSITION 7 IS EI DATATYPE:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/EI
    

    public function setScheduledStationName($value, int $position = 7)
    {
        return $this->setField($position, $value);
    }
    
    // POSITION 8 IS CWE DATATYPE:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/CWE

    public function setScheduledProcedureStepLocation($value, int $position = 8)
    {
        return $this->setField($position, $value);
    }
    
    // POSITION 9 IS ST DATATYPE:  http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html

    public function setScheduledStationAeTitle($value, int $position = 9)
    {
        return $this->setField($position, $value);
    }
    
    
    
    
    
    //  *** GETTERS ***
    // POSITIONS 1 THROUGH 4 ARE EI DATATYPES:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/EI
    
	/* setAccessionIdentifier,  corresponds to the Filler Order
	 * 
     * Entity Identifier
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function getAccessionIdentifier($value, int $position = 1)
    {
        return $this->getField($position, $value);
    }
    /* setRequestedProcedureId
     * Entity Identifier, 16 maximum chars
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function getRequestedProcedureId($value, int $position = 2)
    {
        return $this->getField($position, $value);
    }
    /* setStudyInstanceUid
     * Entity Identifier, 64 maximum chars, unique id generated by the RIS or DICOM 
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function getStudyInstanceUid($value, int $position = 3)
    {
        return $this->getField($position, $value);
    }
    /* setScheduledProcedureStepId
     * Entity Identifier, 16 maximum chars
     * Namespace ID
     * Universal ID
     * Universal ID Type
    */
    public function getScheduledProcedureStepId($value, int $position = 4)
    {
        return $this->getField($position, $value);
    }
    
    
    // POSITIONS 5 & 6 ARE CWE DATATYPES:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/CWE
    
    /* setModality and exam encoding
    
     * (0008,0060) 5.1 is same as this
     * See below for list of valid values for 5.1
     * 5.2 is  descriptive text for exam
     * 5.3 is  Name Of Coding System, see below
     * 5.4 is  Alternate Identifier, see below
     * 5.5 is  Alternate Text, see below
     * 5.6 is  Name Of Alternate Coding System, see below
     * 5.7 is  Name Of Coding System, see below
    */
    public function getModality($value, int $position = 5)
    {
        return $this->getField($position, $value);
    }

    public function getrotocolCode($value, int $position = 6)
    {
        return $this->getField($position, $value);
    }
    
    // POSITION 7 IS EI DATATYPE:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/EI
    

    public function getScheduledStationName($value, int $position = 7)
    {
        return $this->getField($position, $value);
    }
    
    // POSITION 8 IS CWE DATATYPE:  https://hl7-definition.caristix.com/v2/HL7v2.8/DataTypes/CWE

    public function getScheduledProcedureStepLocation($value, int $position = 8)
    {
        return $this->getField($position, $value);
    }
    
    // POSITION 9 IS ST DATATYPE:  http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html

    public function getScheduledStationAeTitle($value, int $position = 9)
    {
        return $this->getField($position, $value);
    }
    
}
/*

MODALITY LIST:

AR Autorefraction
ASMT Content Assessment Results
AU Audio
BDUS Bone Densitometry (ultrasound)
BI Biomagnetic imaging
BMD Bone Densitometry (X-Ray)
CR Computed Radiography
CT Computed Tomography
CTPROTOCOL CT Protocol (Performed)
DG Diaphanography
DOC Document
DX Digital Radiography
ECG Electrocardiography
EPS Cardiac Electrophysiology
ES Endoscopy
FID Fiducials
GM General Microscopy
HC Hard Copy
HD Hemodynamic Waveform
IO Intra-Oral Radiography
IOL Intraocular Lens Data
IVOCT Intravascular Optical Coherence Tomography
IVUS Intravascular Ultrasound
KER Keratometry
KO Key Object Selection
LEN Lensometry
LS Laser surface scan
MG Mammography
MR Magnetic Resonance
M3D Model for 3D Manufacturing
NM Nuclear Medicine
OAM Ophthalmic Axial Measurements
OCT Optical Coherence Tomography (non-Ophthalmic)
OP Ophthalmic Photography
OPM Ophthalmic Mapping
OPT Ophthalmic Tomography
OPTBSV Ophthalmic Tomography B-scan Volume Analysis
OPTENF Ophthalmic Tomography En Face
OPV Ophthalmic Visual Field
OSS Optical Surface Scan
OT Other
PLAN Plan
PR Presentation State
PT Positron emission tomography (PET)
PX Panoramic X-Ray
REG Registration
RESP Respiratory Waveform
RF Radio Fluoroscopy
RG Radiographic imaging (conventional film/screen)
RTDOSE Radiotherapy Dose
RTIMAGE Radiotherapy Image
RTINTENT Radiotherapy Intent
RTPLAN Radiotherapy Plan
RTRAD RT Radiation
RTRECORD RT Treatment Record
RTSEGANN Radiotherapy Segment Annotation
RTSTRUCT Radiotherapy Structure Set
RWV Real World Value Map
SEG Segmentation
SM Slide Microscopy
SMR Stereometric Relationship
SR SR Document
SRF Subjective Refraction
STAIN Automated Slide Stainer
TEXTUREMAP Texture Map
TG Thermography
US Ultrasound
VA Visual Acuity
XA X-Ray Angiography
XC External-camera Photography

Retired Defined Terms:

AS Angioscopy
CD Color flow Doppler
CF Cinefluorography
CP Culposcopy
CS Cystoscopy
DD Duplex Doppler
DF Digital fluoroscopy
DM Digital microscopy
DS Digital Subtraction Angiography
EC Echocardiography
FA Fluorescein angiography
FS Fundoscopy
LP Laparoscopy
MA Magnetic resonance angiography
MS Magnetic resonance spectroscopy
OPR Ophthalmic Refraction
ST Single-photon emission computed tomography (SPECT)
VF Videofluorography
*/

/*

CODING SYSTEMS:  https://hl7-definition.caristix.com/v2/HL7v2.8/Tables/0396

99zzz	Local general code where z is an alphanumeric character	
ACR	American College of Radiology finding codes	
ALPHAID2006	German Alpha-ID v2006	
ALPHAID2007	German Alpha-ID v2007	
ALPHAID2008	German Alpha-ID v2008	
ALPHAID2009	German Alpha-ID v2009	
ALPHAID2010	German Alpha-ID v2010	
ALPHAID2011	German Alpha-ID v2011	
ANS+	HL7 set of units of measure	
ART	WHO Adverse Reaction Terms	
AS4	ASTM E1238/ E1467 Universal	
AS4E	AS4 Neurophysiology Codes	
ATC	American Type Culture Collection	
C4	CPT-4	
CAPECC	College of American Pathologists Electronic Cancer Checklist	
CAS	Chemical abstract codes	
CCC	Clinical Care Classification system	
CD2	CDT-2 Codes	
CDCA	CDC Analyte Codes	
CDCEDACUITY	CDC Emergency Department Acuity	
CDCM	CDC Methods/Instruments Codes	
CDCOBS	CDC BioSense RT observations (Census) - CDC	
CDCPHINVS	CDC PHIN Vocabulary Coding System	
CDCREC	Race & Ethnicity - CDC	
CDS	CDC Surveillance	
CE (obsolete)	CEN ECG diagnostic codes	
CLP	CLIP	
CPTM	CPT Modifier Code	
CST	COSTART	
CVX	CDC Vaccine Codes	
DCM	DICOM Controlled Terminology	
E	EUCLIDES	
E5	Euclides quantity codes	
E6	Euclides Lab method codes	
E7	Euclides Lab equipment codes	
ENZC	Enzyme Codes	
EPASRS	EPA SRS	
FDAUNII	Unique Ingredient Identifier (UNII)	
FDDC	First DataBank Drug Codes	
FDDX	First DataBank Diagnostic Codes	
FDK	FDA K10	
FIPS5_2	FIPS 5-2 (State)	
FIPS6_4	FIPS 6-4 (County)	
GDRG2004	G-DRG German DRG Codes v2004	
GDRG2005	G-DRG German DRG Codes v2005	
GDRG2006	G-DRG German DRG Codes v2006	
GDRG2007	G-DRG German DRG Codes v2007	
GDRG2008	G-DRG German DRG Codes v2008	
GDRG2009	G-DRG German DRG Codes v2009	
GMDC2004	German Major Diagnostic Codes v2004	
GMDC2005	German Major Diagnostic Codes v2005	
GMDC2006	German Major Diagnostic Codes v2006	
GMDC2007	German Major Diagnostic Codes v2007	
GMDC2008	German Major Diagnostic Codes v2008	
GMDC2009	German Major Diagnostic Codes v2009	
HB	HIBCC	
HCPCS	CMS (formerly HCFA) Common Procedure Coding System	
HCPT	Health Care Provider Taxonomy	
HHC	Home Health Care	
HI	Health Outcomes	
HL7nnnn	HL7 Defined Codes where nnnn is the HL7 table number	
HOT	Japanese Nationwide Medicine Code	
HPC	CMS (formerly HCFA )Procedure Codes (HCPCS)	
I10	ICD-10	
I10G2004	ICD 10 Germany 2004	
I10G2005	ICD 10 Germany 2005	
I10G2006	ICD 10 Germany 2006	
I10P	ICD-10 Procedure Codes	
I9	ICD9	
I9C	ICD-9CM	
I9CDX	ICD-9CM Diagnosis codes	
I9CP	ICD-9CM Procedure codes	
IBT	ISBT	
IBTnnnn	ISBT 128 codes where nnnn specifies a specific table within ISBT 128.	
IC2	ICHPPC-2	
ICD10AM	ICD-10 Australian modification	
ICD10CA	ICD-10 Canada	
ICD10GM2007	ICD 10 Germany v2007	
ICD10GM2008	ICD 10 Germany v2008	
ICD10GM2009	ICD 10 Germany v2009	
ICD10GM2010	ICD 10 Germany v2010	
ICD10GM2011	ICD 10 Germany v2011	
ICDO	International Classification of Diseases for Oncology	
ICDO2	International Classification of Disease for Oncology Second Edition	
ICDO3	International Classification of Disease for Oncology Third Edition	
ICS	ICCS	
ICSD	International Classification of Sleep Disorders	
ISO	ISO 2955.83 (units of measure) with HL7 extensions	
ISO3166_1	ISO 3166-1 Country Codes	
ISO3166_2	ISO 3166-2 Country subdivisions	
ISO4217	ISO4217 Currency Codes	
ISO639	ISO 639 Language	
ISOnnnn (deprecated)	ISO Defined Codes where nnnn is the ISO table number	
ITIS	Integrated Taxonomic Information System	
IUPC	IUPAC/IFCC Component Codes	
IUPP	IUPAC/IFCC Property Codes	
JC10	JLAC/JSLM, nationwide laboratory code	
JC8	Japanese Chemistry	
JJ1017	Japanese Image Examination Cache	
L	Local general code	
LB	Local billing code	
LN	Logical Observation Identifier Names and Codes (LOINCÂ®)	
MCD	Medicaid	
MCR	Medicare	
MDC	Medical Device Communication	
MDDX	Medispan Diagnostic Codes	
MEDC	Medical Economics Drug Codes	
MEDR	Medical Dictionary for Drug Regulatory Affairs (MEDDRA)	
MEDX	Medical Economics Diagnostic Codes	
MGPI	Medispan GPI	
MVX	CDC Vaccine Manufacturer Codes	
NAICS	Industry (NAICS)	
NCPDPnnnnsss	NCPDP code list for data element nnnn [as used in segment sss]	
NDA	NANDA	
NDC	National drug codes	
NDFRT	NDF-RT (Drug Classification)	
NIC	Nursing Interventions Classification	
NIP001	Source of Information (Immunization)	
NIP002	Substance refusal reason	
NIP004	Vaccination - Contraindications, Precautions, and Immunities	
NIP007	Vaccinated at location (facility)	
NIP008	Vaccine purchased with (Type of funding)	
NIP009	Reported adverse event previously	
NIP010	VAERS Report type	
NND	Notifiable Event (Disease/Condition) Code List	
NPI	National Provider Identifier	
NUBC	National Uniform Billing Committee	
NULLFL	Null Flavor	
O301	German Procedure Codes	
O3012004	OPS Germany v2004	
O3012005	OPS Germany v2005	
O3012006	OPS Germany v2006	
OHA	Omaha System	
OPS2007	OPS Germany v2007	
OPS2008	OPS Germany v2008	
OPS2009	OPS Germany v2009	
OPS2010	OPS Germany v2010	
OPS2011	OPS Germany v2011	
PHINQUESTION	CDC Public Health Information Network (PHIN) Question	
PLR	CDC PHLIP Lab result codes that are not covered in SNOMED at the time of this implementation	
PLT	CDC PHLIP Lab test codes, where LOINC concept is too broad or not yet available, especially as needed for ordering and or lab to lab reporting )	
POS	POS Codes	
RC	Read Classification	
RXNORM	RxNorm	
SCT	SNOMED Clinical Terms	
SCT2	SNOMED Clinical Terms alphanumeric codes	
SDM	SNOMED- DICOM Microglossary	
SIC	Industry (SIC)	
SNM	Systemized Nomenclature of Medicine (SNOMED)	
SNM3	SNOMED International	
SNT	SNOMED topology codes (anatomic sites)	
SOC	Occupation (SOC 2000)	
UB04FL14	Priority (Type) of Visit	
UB04FL15	Point of Origin	
UB04FL17	Patient Discharge Status	
UB04FL31	Occurrence Code	
UB04FL35	Occurrence Span	
UB04FL39	Value Code	
UC	UCDS	
UCUM	UCUM code set for units of measure(from Regenstrief)	
UMD	MDNS	
UML	Unified Medical Language	
UPC	Universal Product Code	
UPIN	UPIN	
USPS	United States Postal Service	
W1	WHO record # drug codes (6 digit)	
W2	WHO record # drug codes (8 digit)	
W4	WHO record # code with ASTM extension	
WC	WHO ATC	
X12Dennnn	ASC X12 Code List nnnn
*/
