<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrthancHostsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('orthanc_hosts', function (Blueprint $table) {
        
            $table->increments('id');
            $table->string('AET', 16)->nullable();
            $table->string('nginx_admin_url', 128)->nullable();
            $table->string('api_url', 128)->nullable();
            $table->string('osimis_viewer_link', 128)->nullable();
            $table->string('osimis_viewer_check', 128)->nullable();
            $table->string('server_name', 32)->nullable();
            $table->string('osimis_viewer_name', 32)->nullable();
            $table->string('domain', 64)->nullable();
            $table->tinyInteger('stone_viewer')->nullable();

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('orthanc_hosts');
    }
}
